platform: linux
image_resource:
  type: registry-image
inputs:
  - name: abi_test_src
  - name: gpdb_src
  - name: tt_src
  - name: bin_gpdb
  - name: bin_gpdb_clients
outputs:
  - name: sqldump
params:
  DUMP_DB: "false"
  MAKE_TEST_COMMAND: ""
  BLDWRAP_POSTGRES_CONF_ADDONS: ""
  TEST_OS: ""
  CONFIGURE_FLAGS: ""
  WITH_MIRRORS:
  COPY_TEST: ""
run:
  path: abi_test_src/concourse/scripts/sha256_abi_test.bash
